"""Brand, bridge, color

Revision ID: 58b5e58655a1
Revises: 
Create Date: 2023-12-10 06:06:25.151770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b5e58655a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('founded_in', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('colors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum('FIXED', 'HEADLESS', 'VINTAGE_TREMOLO', 'TWO_POINT_TREMOLO', 'FOUR_POINT_TREMOLO', 'FLOATING_TREMOLO', 'TUNE_O_MATIC', name='bridge_type'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bridges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('year_of_introduction', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bridges_colors',
    sa.Column('color_id', sa.UUID(), nullable=False),
    sa.Column('bridge_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bridge_id'], ['bridges.id'], ),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ),
    sa.PrimaryKeyConstraint('color_id', 'bridge_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bridges_colors')
    op.drop_table('bridges')
    op.drop_table('colors')
    op.drop_table('brands')
    # ### end Alembic commands ###
