"""cascade_delete

Revision ID: 8c54f414f231
Revises: cb09dd07758d
Create Date: 2023-12-31 16:06:35.433960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c54f414f231'
down_revision: Union[str, None] = 'cb09dd07758d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('auth_user_id_fkey', 'auth', type_='foreignkey')
    op.create_foreign_key(None, 'auth', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('bridges', 'brand_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint('bridges_brand_id_fkey', 'bridges', type_='foreignkey')
    op.create_foreign_key(None, 'bridges', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('bridges_colors_color_id_fkey', 'bridges_colors', type_='foreignkey')
    op.drop_constraint('bridges_colors_bridge_id_fkey', 'bridges_colors', type_='foreignkey')
    op.create_foreign_key(None, 'bridges_colors', 'bridges', ['bridge_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'bridges_colors', 'colors', ['color_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bridges_colors', type_='foreignkey')
    op.drop_constraint(None, 'bridges_colors', type_='foreignkey')
    op.create_foreign_key('bridges_colors_bridge_id_fkey', 'bridges_colors', 'bridges', ['bridge_id'], ['id'])
    op.create_foreign_key('bridges_colors_color_id_fkey', 'bridges_colors', 'colors', ['color_id'], ['id'])
    op.drop_constraint(None, 'bridges', type_='foreignkey')
    op.create_foreign_key('bridges_brand_id_fkey', 'bridges', 'brands', ['brand_id'], ['id'])
    op.alter_column('bridges', 'brand_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(None, 'auth', type_='foreignkey')
    op.create_foreign_key('auth_user_id_fkey', 'auth', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
